# Generated by Django 5.0 on 2026-09-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_achievements_educations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='display_order',
        ),
        migrations.AlterField(
            model_name='achievements',
            name='rank',
            field=models.CharField(choices=[('finalist', 'Finalist'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=10),
        ),
        migrations.AlterField(
            model_name='experience',
            name='skills',
            field=models.TextField(blank=True, default=''),
        ),
    ]
