# Generated by Django 5.0 on 2026-09-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_achievements_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='org_logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
